version: 2
updates:
  - package-ecosystem: yarn
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependabot

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependabot
